// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQb7hoQW3YZ9WBlWDunULv5G7u9FgAVaw',
    appId: '1:836214752700:web:8597441c430d23b81717b9',
    messagingSenderId: '836214752700',
    projectId: 'chatters-6b22a',
    authDomain: 'chatters-6b22a.firebaseapp.com',
    storageBucket: 'chatters-6b22a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EmeEK-lF5B9zMz3I8-FNkAUbJtwnfOM',
    appId: '1:836214752700:android:2399bb524f3937401717b9',
    messagingSenderId: '836214752700',
    projectId: 'chatters-6b22a',
    storageBucket: 'chatters-6b22a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIeyqlFW51-e9Tq7s2Aj6p047FqrTpmg',
    appId: '1:836214752700:ios:f6bdd44b17c1f3591717b9',
    messagingSenderId: '836214752700',
    projectId: 'chatters-6b22a',
    storageBucket: 'chatters-6b22a.appspot.com',
    androidClientId: '836214752700-0pcehjnq9ccgelubm7vkosmko7ok3vib.apps.googleusercontent.com',
    iosClientId: '836214752700-vst1pee0bnf558bt2jrqh4fvkcpj6vbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatters2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcIeyqlFW51-e9Tq7s2Aj6p047FqrTpmg',
    appId: '1:836214752700:ios:2d7131dc55ad24b51717b9',
    messagingSenderId: '836214752700',
    projectId: 'chatters-6b22a',
    storageBucket: 'chatters-6b22a.appspot.com',
    androidClientId: '836214752700-0pcehjnq9ccgelubm7vkosmko7ok3vib.apps.googleusercontent.com',
    iosClientId: '836214752700-s43c1bulrhm0jpr6jl3qfro74usnvi22.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatters2.RunnerTests',
  );
}
